language: java
dist: xenial

script:
- cd sample
- mvn clean verify
- cd ../
- cp sample/target/sample.war .
- cp sample/target/liberty/wlp/usr/servers/defaultServer/server.xml .
- cp sample/target/liberty/wlp/usr/shared/resources/mysql-*.jar .
- docker build -t $DOCKER_USERNAME/sample:1.0 .

after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    docker push $DOCKER_USERNAME/sample:1.0;
  fi

notifications:
  slack: secure: "FoSaWRMLHYFrb/K01KVLmlWV3iKUBYzmLkJjUfWWySQxtzd8dM6GnbGRCoH5ZdVOCa9mj06RjioCFRozA9HGOsC2Hlo3NK8Do0hY1reUA31RN5t47tDs3CC5B8WTwdDhK1ZfQcWTNLOQdkCgNGyovmtXVLSZe0dIhVfllEkTJzccI2XHjzPhP4fEVqya/xXBn79hanZpUZwez3/+LaRjMwy9LuaXu9Pw4uGVd0wgQcfoPzPTcuxgHkFYY4QIS3ZwjBkm1sSS2+mfS6ZWlvZUo4T42QOmyg46tSeJieYZeFR4P342M/pnYV7zOf75iLVfNPDf6XCaOp1ryx6h9JCXZ/TIU8b+ovsRp6UtQPZ4okP3n0SKlZdZqaoxv+ytzg5sI83I+EjHhh4EX8jeqi4U6n4LikI/zjnsd4tZhfeOwBgaXHP8XDH5QTzGvkK2Ly4YSCySHrxUgYFjV0zH3EoirYG2ETybGQ8OWlK81CPkxsHjIj7vTz3RQPWa6ByZFa4AdJbdmcSmSDdmNfrV7WUaZ0dtAEma4S7ykWnrGUSWovSht4VQcuPIN/H2ikrC4c18WDFmu5rsQH9ZoTpnqYg30+NtVFNDNlkv3/9lwTr4gkDB38dWuCZ/2TpjOOdr8HeB9cbOorSQQ7kXkQ/seN/CZLtcqRzbjSxMr1l5vKtoMQw="
