language: java
dist: xenial

script:
- mkdir -p build
- cd sample
- mvn clean verify
- cd ../build/
- cp ../sample/Dockerfile .
- cp ../sample/target/sample.war .
- cp ../sample/target/liberty/wlp/usr/servers/defaultServer/server.xml .
- cp ../sample/target/liberty/wlp/usr/shared/resources/mysql-*.jar .
- docker build -t $DOCKER_USERNAME/sample:1.0 .

after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    docker push $DOCKER_USERNAME/sample:1.0;
  fi

notifications:
  slack:
    secure: "oSRK+tFzP/scAyKrz5avI+q4rnjSfK4H2kTe6+c2ve4prcQ41vcUJzo9WhyLGZBkSRUeVqXQHf5JNFhowxFkYXq40f6lP3g/HqkjaK5SqYQg1MCuDKQ8/yWqOOTGxDWgdZIWGUCLPCPTHQC4hQXn61pzhQPanmqS0fvATclSKTmI8JWEbJxJfc1WptigLQQUg4/Y2wto4Me7BDs553uXQ3aehOsB5GEc6UI7y9/u+hUKvI5bBNHf00N8DhWlUyu6l7tskMETsIizRw9R/vLlZLrHnkkFMlPKkyTbiQLBe79Pxa7/mZ2Q6EDYw19xfDU8RXTRNDdIVY5K9P5rvCUHIWy/hsSn7PqneZVp2yjv5cnpfveqpo+9d1rcJbHJMbD1+qzprdZvFjggHkJl8fcGQhKNUEFNfPuMrLxTfFur7eDyc3cwyLFQIVcC6aKj6zm1pgU4U7XBq7evaotao3DJFVU2Y4UvYNUcXnc0MI1zDq8V1s7D29VVF9COF1mx3Ton+4C6BG/QuDW/5a0lQ/WJMOvYcTE7p9KnHEiICmlem1bFRv9u3OJWv7TCrtfczkG4+20eH2eLp+D7hZZTITH7WURz45w310yx0MHEsZ+2cSDZik8KQqCMWPm8B1lvAP6svnXZf6H2zhkazcafRyjkyg82gBKTK2fqs8BLASptpf4="
