language: java
dist: xenial
script:
- cd sample
- mvn clean verify
- cd ../
- cp sample/target/sample.war .
- cp sample/target/liberty/wlp/usr/servers/defaultSever/server.xml .
- cp sample/target/liberty/wlp/usr/shared/resources/mysql-*.jar .
- docker build -t $DOCKER_USERNAME/sample:1.0 .
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker
  push $DOCKER_USERNAME/sample:1.0; fi
notifications:
  slack:
    secure: kxWX+SxaEKY0QJ2KRK5rL7lVXB9rIk+Y9zu2HhvcoJ0kNJLiGdQ9YDAGqX7vlXx50XYzGMlsga6pFhaJuHfx30lLCTuHobn4tqkRJ2qlqr1a61FbqLP/XcwO9t1eug8AG30HI98/stnIc9JMyqNOc/0MujxqvRLUbgN7jP2Slu0KIDfsPnOvrTiA2r/Fsv18aT9681YDDSLbkzBQn8RYItaK+5BiSasbiklAlCujPLS8On6FP0GPPnM9dqu33wzzaBXg6a6dsdA8pk0qVyqKjPySAOjdPqTQ++9E11koE1CGg/oJAonanrsrCSlnJ96uMjd1iV8SzoGbHP/yqphRhKtfCvdyCZaMHIS3XdDqWE1IuYhGYHAeZ32ZV4ICeXawNktRAvvF1mJ74H5CimyCY7mHVZWqmcQNvuhNWvQ4JSOuq7hfKBua3YWny+TOWZCcGXa2brbyEk/yIao/1Uuv29iZa3PY2V6FLPHml4RZu4to1R36XvLk69UvoLiGY98CVJpY8I9L4jyp3zh2pywNL5mkoV0l3qlYNmM6I07pJAAuI5CJe3aZlpZxb8Yhz4xN3s9KgBkhUiyHVsyhlU5sqV4dHhdhavDGYcYIrUG9vVz1DCZheVqMldWHaxAj7xeGeOZMivg/55ynWP+r7q5w0TMbWpEzfgzVc4vkfQQiCfw=
secure: e27sBafiz2YswxuYQDdt91SXqU/YUpmVY9JkUM8uOkvEj7fwM1ibumPVSfYBJ/pg5KSwIBcsbjIRVie2uFhZ/kFL8N3rjLw7UHIEOqh3m3Q9n2yOzcXG2loYyHMrM6CwK8K3oStRwkbGrwLJHWhRsF9019okEsU2m+Ij+8SZDBlnVAMkBsQKihLFgt45G4E9N/YQT3egKopaTC9So5hXuh9Rx5wPfmE5kH0vydv72WHY3HDxjq7EMDoPytlDfrX06BwV5HY1p3so0PlGQLwpdzQepN67RbcjMLt9VvLmD55/2lcoIGdnr5iUwKyxtO8DNya5PjRXLmIM3zwJsUZY62wPxA3bGHatxnXqonwmzmqk7Kp+0tdsg19F3YhQNB0N3HAnvH5wxtnfXV/5g2Y7zg7Z+/I+mziYpVV/W9SYCgZKqq8hwl6jSWauGe7TZQtOwNmti3Ttk4PmHlNL6ZPzeufZTPgbxkPxqbU9DXjS7p7aFcSmMuykp3R1piDbshwDTdGeK4mEQVwci5LSGJ3MfQdHYha32xVb4hUuAukNz3EPCDLUR7cNIRJjZKn8xSdK6nCPDMQ4bxXQOmVV8uDv0rGpE58eftQau8ZZ+tq/wCNES7GGAneWgrWDyzrEHDixQRfqPnGNul7sLGpf+tyUnH91fJ4NljBgvJ8yctk+yis=
